%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(hbase_types).

-include("hbase_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('tCell') ->
  {struct, [{1, string},
          {2, i64}]}
;

struct_info('columnDescriptor') ->
  {struct, [{1, string},
          {2, i32},
          {3, string},
          {4, bool},
          {5, string},
          {6, i32},
          {7, i32},
          {8, bool},
          {9, i32}]}
;

struct_info('tRegionInfo') ->
  {struct, [{1, string},
          {2, string},
          {3, i64},
          {4, string},
          {5, byte},
          {6, string},
          {7, i32}]}
;

struct_info('mutation') ->
  {struct, [{1, bool},
          {2, string},
          {3, string},
          {4, bool}]}
;

struct_info('batchMutation') ->
  {struct, [{1, string},
          {2, {list, {struct, {'hbase_types', 'mutation'}}}}]}
;

struct_info('tIncrement') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i64}]}
;

struct_info('tColumn') ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'tCell'}}}]}
;

struct_info('tRowResult') ->
  {struct, [{1, string},
          {2, {map, string, {struct, {'hbase_types', 'tCell'}}}},
          {3, {list, {struct, {'hbase_types', 'tColumn'}}}}]}
;

struct_info('tScan') ->
  {struct, [{1, string},
          {2, string},
          {3, i64},
          {4, {list, string}},
          {5, i32},
          {6, string},
          {7, bool}]}
;

struct_info('iOError') ->
  {struct, [{1, string}]}
;

struct_info('illegalArgument') ->
  {struct, [{1, string}]}
;

struct_info('alreadyExists') ->
  {struct, [{1, string}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('tCell') ->
  {struct, [{1, undefined, string, 'value', undefined},
          {2, undefined, i64, 'timestamp', undefined}]}
;

struct_info_ext('columnDescriptor') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, undefined, i32, 'maxVersions', 3},
          {3, undefined, string, 'compression', "NONE"},
          {4, undefined, bool, 'inMemory', false},
          {5, undefined, string, 'bloomFilterType', "NONE"},
          {6, undefined, i32, 'bloomFilterVectorSize', 0},
          {7, undefined, i32, 'bloomFilterNbHashes', 0},
          {8, undefined, bool, 'blockCacheEnabled', false},
          {9, undefined, i32, 'timeToLive', -1}]}
;

struct_info_ext('tRegionInfo') ->
  {struct, [{1, undefined, string, 'startKey', undefined},
          {2, undefined, string, 'endKey', undefined},
          {3, undefined, i64, 'id', undefined},
          {4, undefined, string, 'name', undefined},
          {5, undefined, byte, 'version', undefined},
          {6, undefined, string, 'serverName', undefined},
          {7, undefined, i32, 'port', undefined}]}
;

struct_info_ext('mutation') ->
  {struct, [{1, undefined, bool, 'isDelete', false},
          {2, undefined, string, 'column', undefined},
          {3, undefined, string, 'value', undefined},
          {4, undefined, bool, 'writeToWAL', true}]}
;

struct_info_ext('batchMutation') ->
  {struct, [{1, undefined, string, 'row', undefined},
          {2, undefined, {list, {struct, {'hbase_types', 'mutation'}}}, 'mutations', []}]}
;

struct_info_ext('tIncrement') ->
  {struct, [{1, undefined, string, 'table', undefined},
          {2, undefined, string, 'row', undefined},
          {3, undefined, string, 'column', undefined},
          {4, undefined, i64, 'ammount', undefined}]}
;

struct_info_ext('tColumn') ->
  {struct, [{1, undefined, string, 'columnName', undefined},
          {2, undefined, {struct, {'hbase_types', 'tCell'}}, 'cell', #tCell{}}]}
;

struct_info_ext('tRowResult') ->
  {struct, [{1, undefined, string, 'row', undefined},
          {2, optional, {map, string, {struct, {'hbase_types', 'tCell'}}}, 'columns', dict:new()},
          {3, optional, {list, {struct, {'hbase_types', 'tColumn'}}}, 'sortedColumns', []}]}
;

struct_info_ext('tScan') ->
  {struct, [{1, optional, string, 'startRow', undefined},
          {2, optional, string, 'stopRow', undefined},
          {3, optional, i64, 'timestamp', undefined},
          {4, optional, {list, string}, 'columns', []},
          {5, optional, i32, 'caching', undefined},
          {6, optional, string, 'filterString', undefined},
          {7, optional, bool, 'sortColumns', undefined}]}
;

struct_info_ext('iOError') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('illegalArgument') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('alreadyExists') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

